name: Docker Layer Caching
description: ''
branding:
  icon: layers
  color: blue
inputs:
  repotag:
    description: The image repotag to be cached.
    required: true
  key:
    description: The key name to store cache.
    required: true
runs:
  using: node12
  main: dist/ttsc-dist/main.js/index.js
  post: dist/ttsc-dist/post.js/index.js
