name: CI

on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo 'ref: ${{ github.ref }}, sha: ${{ github.sha }}'
            jq '.' <<<"${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }}
