name: 'Docker Bakery Test'
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      REGISTRY_REDIS_PASSWORD: "SomePass0987"
      REDIS_PASSWORD: "SomePass0987"
      REGISTRY_PROXY_PASSWORD: ${{ github.token }}
      REGISTRY_VOLUME: /tmp/cache/registry
      REDIS_VOLUME: /tmp/cache/redis
    permissions:
      packages: write
      contents: read
      actions: read
    services:
      registry-redis:
        image: redis
        volumes:
          - /tmp/cache/redis:/data
        env:
          REDIS_PORT: 6379
          REDIS_HOST: registry-redis
          REDIS_DB: 0
          REDIS_PASSWORD: "SomePass0987"
          REGISTRY_REDIS_PASSWORD: "SomePass0987"
          REDISCLI_AUTH: "SomePass0987"
        options: >-
          --cap-add "sys_resource"
          --restart always
          --entrypoint "redis-server --save 60 1 --loglevel warning --requirepass SomePass0987"
      registry:
        image: registry:2
        ports:
          - "5000:5000/tcp"
        volumes:
          - /tmp/cache/registry:/var/lib/registry
        env:
          REGISTRY_LOG_LEVEL: warn
          REGISTRY_PROXY_PASSWORD: ${{ github.token }}
          REGISTRY_REDIS_PASSWORD: "SomePass0987"
          REGISTRY_PROXY_REMOTEURL: https://ghcr.io
          REGISTRY_PROXY_USERNAME: $
          REGISTRY_REDIS_ADDR: registry-redis:6379
          REGISTRY_REDIS_DB: 0
          REGISTRY_REDIS_DIALTIMEOUT: 100ms
          REGISTRY_REDIS_READTIMEOUT: 100ms
          REGISTRY_REDIS_WRITETIMEOUT: 100ms
          REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
          REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
          REGISTRY_REDIRECT_DISABLE: true
          REGISTRY_HTTP_SECRET: "SomePass0987"
          REGISTRY_HTTP_HTTP2_DISABLED: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: check docker daemon config
        run: |
          tmp_file=$(mktemp)
          jq '."insecure-registries" = ["127.0.0.1:5000"] | ."registry-mirrors" = [ "http://127.0.0.1:5000" ]' /etc/docker/daemon.json | tee "${tmp_file}" && sudo mv "${tmp_file}" /etc/docker/daemon.json
          sudo systemctl restart docker
          docker exec -it registry-redis redis-cli save


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            broadshield/action-docker-layer-caching
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: GitHub meta
        id: github-meta
        uses: dockerbakery/github-metadata-action@v1

      - uses: docker/bake-action@v2
        with:
          files: |
            ./__tests__/docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
            ${{ steps.github-meta.outputs.bake-file }}
          targets: build
